spring:
  ldap:
    urls: ldaps://localhost:10636
    base: dc=example,dc=com
    username: uid=admin,ou=system
    password: secret

server:
  ssl:
    key-store: classpath:apacheds.jks
    key-store-password: keystorepassword
    key-store-type: PKCS12
    key-alias: apacheds
    trust-store: classpath:truststore.jks
    trust-store-password: truststorepassword
    trust-store-type: PKCS12
  port: 8443


logging:
  level:
    org:
      springframework:
        ldap: DEBUG
        security: DEBUG
    root: INFO
